### ISSUE TITLE
Relay vs minimongo

### ISSUE THREAD

**Issue by hluz** [meteor/data#4] opened 2016-01-28 08:47 UTC
Lots of questions on cached local data...
 
Will Meteor Data (GraphQL [+ Relay?] based) replace or complement minimongo? if it replaces, can Relay provide the capability to query and manipulate cached data similarly to minimongo?  Including the capability to use local only "collections"? If so, will GraphQL also have the capability to query and mutate local "collections"? These capabilities are quite commonly used now...

**Comment by Goatic** [comment] 2016-01-28 11:12
The model for isomorphic DB queries is awesome IMO. I think you should consider utilizing client side graphQL queries, in the same way we do MiniMongo Queries right now :+1: 

This would allow me to easily define my schemas in an isomorphic module, and import it to both frontend and backend.

I imagine this kind of approach would also require a data cache on the client that would be built around graphQL, no? I think this would be a good approach

**Comment by batjko** [comment] 2016-01-28 13:41
I think if GraphQL does replace Mongo/MiniMongo as the default data infrastructure, we won't have "collections" per se, but for the sake of latency compensation we'll definitely have to have some local, reactive result-set of a GraphQL service that gets synced with the server behind the scenes. 
There's no way around that, as that's one of the 'raisons d'etre' of Meteor itself.

Once we have that, client-only versions of this new result-set object is surely implied with that.

**Comment by ramsaylanier** [comment] 2016-01-28 14:14
Yeah, I think with a Relay/GraphQL solution, client side collections will not be necessary. And, though I'm still kinda new with Relay, you'd have to have the ability to create GraphQL mutations that only affect local state and then replicate it on the server when possible.

**Comment by hluz** [comment] 2016-01-28 22:57
> Yeah, I think with a Relay/GraphQL solution, client side collections will not be necessary.

Well, this is one of my points. While I can see that for specific use cases (mobile, Facebook style or forums/discussion apps whose page data requirements are basic and can be satisfied only to graph structures) GraphQL + Relay can be a good fit, those types of app are not representative of the needs of Web Applications (not only mobile apps) on the Enterprise world. These later ones need extensive data querying and manipulation capabilities of both data stored in existing database(s) and local data.

SPA  web applications that don't fit the simple pattern that GraphQL+Relay appear to have been created for, need query and data manipulation capabilities **on the client** for cached data, and can't see how we can do that without some sort of "collections" (arrays of related objects that can be queried, filtered, transformed, merged, sorted, mapped and used as data sources for UI Components). Enterprise type applications are data-rich and data-driven in a way that is not apparent in the simple mobile web. And irrespective of the size and scale of Facebook (the Facebook social network client, not the company), it is a very simple application compared even with the most basic of an Enterprise application.

**Comment by hluz** [comment] 2016-01-28 23:24
> I think if GraphQL does replace Mongo/MiniMongo as the default data infrastructure, we won't have "collections" per se, but for the sake of latency compensation we'll definitely have to have some local, reactive result-set of a GraphQL service that gets synced with the server behind the scenes. 
There's no way around that, as that's one of the 'raisons d'etre' of Meteor itself.

Agree. I just can't see both GraphQL and Relay being able to give us that. At least at this stage of immaturity. And betting all our money on such immature specifications is definitely very high risk.

**Comment by justinsb** [comment] 2016-01-29 00:01
You will be able to use Reactive GraphQL alongside the existing LiveQuery/MiniMongo stack.

**Comment by ianserlin** [comment] 2016-01-29 03:25
> (arrays of related objects that can be queried, filtered, transformed, merged, sorted, mapped and used as data sources for UI Components)
(from @hluz)

Totally agree. It's not necessarily a question of whether you use minimongo's mongo syntax to accomplish that or not. Simply that there still is some nicely designed API for accomplishing those things on the client-side cache. All of that heavy duty work can supposedly can be done by the resolver (the thing that actually fulfills the GraphQL query) directed by field arguments (https://facebook.github.io/graphql/#sec-Language.Query-Document.Arguments). The question is then, which api will be nicer to write against?

There are at least two (probably more) question here related to the graphql-meteor implementation:

* The syntax for specifying a query against the client-side cache vs against the server/database.
* If field arguments (or some other GraphQL syntax) is really a nice way to sort, filter/query, merge, etc.

We'll see when we use it.

**Comment by hluz** [comment] 2016-01-29 04:51
> You will be able to use Reactive GraphQL alongside the existing LiveQuery/MiniMongo stack.

So confirming: The answer to my first question is that "Reactive GraphQL" (GraphQL + Relay?) will complement LiveQuery/minimongo, not replace it. That's cool. :-)

**Comment by hluz** [comment] 2016-01-29 04:55
> There are at least two (probably more) question here related to the graphql-meteor implementation:
- The syntax for specifying a query against the client-side cache vs against the server/database.
- If field arguments (or some other GraphQL syntax) is really a nice way to sort, filter/query, merge, etc.
We'll see when we use it.

Indeed. But it does not appear to be too functional at this stage. See https://github.com/meteor/data/issues/5

**Comment by justinsb** [comment] 2016-01-29 05:41
Remaining concerns appear to be a duplicate of #5.  Closing as such.

**Closed by justinsb** 2016-01-29 05:41 UTC

**Comment by steph643** [comment] 2016-01-30 11:06
> You will be able to use Reactive GraphQL alongside the existing LiveQuery/MiniMongo stack.

Well, @hluz seems to be happy with this answer, but I am not so convinced.

Let's consider a real case: clients need to show a shared list of items, with reactive insertion, modification and deletion. In that case, it is common for clients to store locally, for each item, a bunch of UI and pre-computed data: check states, color states, visibility states, sanitized string, translated strings, and even heavier stuff.

Note that, in many cases:
- you might not wadon't want to perform those pre-computation server-side for scaling reasons,
- you can't perform those pre-computation on server because they depend on the app local state,
- you can't implement those computation through reactive functions for performance reasons. In Meteor, with only 100 items in the list, and 10 moderately-heavy reactive sources each, your app is already unusable.

The way you solve this in Meteor is by mirroring your server collection into a local collection using an observer. This is quite easy, very efficient, and the code is clean because you can share queries and APIs among the server collection and the local mirror.

Now what happens with the newly envisioned paradigm?

**Comment by hluz** [comment] 2016-01-30 11:59
> Well, @hluz seems to be happy with this answer, but I am not so convinced

@steph643: Not convinced (or otherwise). Guess we will see when details of Reactive GraphQL (is this the official name?) are available... 

Although it still feels like the expectation is that the data graph is to be aligned with the rendered page. As if the only objective of Reactive GraphQL is to provide all the data needed for the current page. Just like a composite REST interface. I've even read the opinion somewhere that It should have Routing capabilities so that when a when a new Route is triggered the data required is then to be retrieved from the Server (shades of Iron-Router subscriptions?). If this is the case, it may be a bit naive for Enterprise-grade/Line-of-Business web applications and a few steps back from where we are now. But keeping an open mind at this stage, specially if like promised we will not loose minimongo and the capability to define local only collections.

**Comment by steph643** [comment] 2016-01-30 13:28
@hluz, I fully agree.
@justinsb, @stubailo, maybe we could reopened this issue (with a clearer title), so that we can keep an eye on it?

**Comment by stubailo** [comment] 2016-01-31 18:25
What would you like the title to be? There have been a could of topics discussed here, let's pick one and stick to it.

**Comment by steph643** [comment] 2016-02-01 12:25
This topic could be renamed into something like "easily binding local data to server data".

**Comment by stubailo** [comment] 2016-02-01 18:23
> easily binding local data to server data

This seems pretty vague, what do you mean by it?

**Comment by steph643** [comment] 2016-02-01 19:19
@stubailo, you'd almost got me with your previous one, but this one is even better, I give up :-)
